name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradle
        run: chmod +x gradle

      - name: Grant rights build.gradle
        run: chmod +x build.gradle.kts

      - name: Build with Gradle
        id: build
        run: gradle build